/*
 *	Author 		: root
 *  Description : auto generated script 
 */
DECLARE
	c_LOG_FILE_NAME VARCHAR2(30) := 'ACCOUNT.txt';
	v_ExistCount NUMBER := 0;
	v_oFile UTL_FILE.FILE_TYPE;
	v_STAGE NUMBER := 0;
	v_STAGE_TITLE VARCHAR2(50) := '';
BEGIN
	v_oFile := UTL_FILE.FOPEN('CSV_OUTPUT_DIR',c_LOG_FILE_NAME,'a');
	UTL_FILE.PUTF(v_oFile,'-------MASTER CREATE : Start Time %s-------%\n',TO_CHAR(SYSTIMESTAMP, 'HH12:MI:SS.FF4 AM'));
			
	--STEP-1-START-CREATE MASTER TABLE
		v_STAGE  := 101;
		v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_MASTER';
	
		
		SELECT COUNT(*) INTO v_ExistCount FROM user_tables
		WHERE TABLE_NAME = 'MASTER';
	
		IF (v_ExistCount = 1 ) THEN
			v_STAGE  := 102;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_DELETE_MASTER';
			EXECUTE IMMEDIATE 'DROP TABLE MASTER';
		END IF;
		
		--IF (v_ExistCount = 0 ) THEN
			v_STAGE  := 103;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_MASTER';
			
			EXECUTE immediate 
			'CREATE TABLE "MASTER"
			(
			 "POST_UR_ID" NUMBER(4, 0),
			 "POST_UR_TIME" NUMBER(4, 0),
			 "PASS_UR_ID" NUMBER(4, 0),
			 "PASS_UR_TIME" NUMBER(4, 0),
			 "BR_CODE" NUMBER(4, 0),
			 "ACTNO" VARCHAR2(13),
			 "STATUS" VARCHAR2(1),
			 "RSTATUS" VARCHAR2(1),
			 "IR_NO" NUMBER(6, 0),
			 "TRAN_DATE" DATE,
			 "TRAN_NO" NUMBER(6, 0),
			 "CATA_CODE" VARCHAR2(4),
			 "CUST_ID" VARCHAR2(13),
			 "MINOR_CUSTID" VARCHAR2(13),
			 "SH_NAME" VARCHAR2(20),
			 "LONG_NAME" VARCHAR2(40),
			 "F_NAME" VARCHAR2(20),
			 "M_NAME" VARCHAR2(20),
			 "L_NAME" VARCHAR2(20),
			 "CONST_CODE" VARCHAR2(1),
			 "GUAR_NAME" VARCHAR2(35),
			 "GUAR_REL" VARCHAR2(1),
			 "ATTACH_CODE" VARCHAR2(1),
			 "FREEZ_CODE" VARCHAR2(1),
			 "RISK_CATA" VARCHAR2(1),
			 "KYC_FLAG" VARCHAR2(1),
			 "AC_OP_DATE" DATE,
			 "OPRN_MODE" VARCHAR2(1),
			 "NPA_TAG" VARCHAR2(1),
			 "INTRO_ACTNO" VARCHAR2(13),
			 "NOMI_NAME" VARCHAR2(35),
			 "NOMI_REL" VARCHAR2(20),
			 "MINOR_TAG" VARCHAR2(1),
			 "MG_NAME" VARCHAR2(35),
			 "MG_REL" VARCHAR2(1),
			 "MINOR_BIRTH_DT" DATE,
			 "DORMANT_TAG" VARCHAR2(1),
			 "FLASH_MESSG" VARCHAR2(35),
			 "TYPEOFAC" VARCHAR2(1),
			 "INSTCODE" VARCHAR2(7),
			 "ISDEAF" VARCHAR2(1),
			 "INT_UPTO_DT" DATE,
			 "INT_ALLOW" NVARCHAR2(1),
			 "OLD_ACTNO" VARCHAR2(25),
			 "STP_TRAN" VARCHAR2(1),
			 "SPC_AC"	VARCHAR2(1),
			 "SH_CIBIL" VARCHAR2(1),
			 "WRTN_OFF_ST" VARCHAR2(1),
			 "SUIT_FLD_ST" VARCHAR2(1),
			 "CLOSE_DT" DATE,
			 "TOTAL_WTN_OFF" NUMBER(15, 2),
			 "PRN_WTN_OFF" NUMBER(15, 2),
			 "WTN_SETTL_AMT" NUMBER(15, 2)
			)';
			   
		   --STEP-1.1-START-ALTER DESTINATION TABLE
				v_STAGE  := 104;
				v_STAGE_TITLE  := 'DESTINATION_TABLE_ALTER_MASTER';
				
				
				SELECT COUNT(*) INTO v_ExistCount FROM user_tab_columns
				WHERE TABLE_NAME = 'MASTER' AND COLUMN_NAME = 'TBL_TYPE';
				
				IF (v_ExistCount = 0 ) THEN
					v_STAGE  := 105;
						EXECUTE IMMEDIATE 'ALTER TABLE MASTER ADD (TBL_TYPE VARCHAR2(20) NULL)';													
				END IF;
				
				SELECT COUNT(*) INTO v_ExistCount FROM user_tab_columns
				WHERE TABLE_NAME = 'MASTER' AND COLUMN_NAME = 'REF_KEY1';
				
				IF (v_ExistCount = 0 ) THEN
					v_STAGE  := 105;
						EXECUTE IMMEDIATE 'ALTER TABLE MASTER ADD (REF_KEY1 NUMBER(7,0) NULL)';
					v_STAGE  := 106;
						EXECUTE IMMEDIATE 'CREATE INDEX "MASTER_REFKEY_BE_IDX1" ON  "MASTER" ("REF_KEY1")';											
				END IF;
				
				-- CREATE INDEX 
				SELECT COUNT(*) INTO v_ExistCount FROM USER_INDEXES
				WHERE INDEX_NAME = 'MASTER_BE_IDX1';
				
				IF( v_ExistCount = 0 ) THEN
					v_STAGE  := 107;
					EXECUTE IMMEDIATE 'CREATE INDEX "MASTER_BE_IDX1" ON  "MASTER" ("ACTNO")';									
				END IF;		

				
				
				
			
			--STEP-1.1-END-ALTER DESTINATION TABLE
	  --END IF;
	--STEP-1-END-CREATE MASTER TABLE
	
	
	
	--STEP-3-START-CREATE CUSTREL TABLE
		v_STAGE  := 301;
		v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_CUSTREL';
	
		
		SELECT COUNT(*) INTO v_ExistCount FROM user_tables
		WHERE TABLE_NAME = 'CUSTREL';
	
		IF (v_ExistCount = 1 ) THEN
			v_STAGE  := 302;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_DELETE_CUSTREL';
			EXECUTE IMMEDIATE 'DROP TABLE CUSTREL';
		END IF;
		
		--IF (v_ExistCount = 0 ) THEN
			v_STAGE  := 303;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_CUSTREL';
			
			EXECUTE immediate 
			'CREATE TABLE "CUSTREL"
			(
			 "ACTNO" VARCHAR2(13),
			 "IR_NO" NUMBER(6, 0),
			 "CUST_ID" VARCHAR2(13),
			 "SR_NO" NUMBER(2, 0)
			)';
			   
		   --STEP-3.1-START-ALTER DESTINATION TABLE
				v_STAGE  := 304;
				v_STAGE_TITLE  := 'DESTINATION_TABLE_ALTER_CUSTREL';
				
				SELECT COUNT(*) INTO v_ExistCount FROM user_tab_columns
				WHERE TABLE_NAME = 'CUSTREL' AND COLUMN_NAME = 'REF_KEY1';
				
				IF (v_ExistCount = 0 ) THEN
					v_STAGE  := 305;
						EXECUTE IMMEDIATE 'ALTER TABLE CUSTREL ADD (REF_KEY1 NUMBER(7,0) NULL)';
					v_STAGE  := 306;
						EXECUTE IMMEDIATE 'CREATE INDEX "CUSTREL_REFKEY_BE_IDX1" ON  "CUSTREL" ("REF_KEY1")';						
					
				END IF;
			--STEP-3.1-END-ALTER DESTINATION TABLE
	  --END IF;
	--STEP-3-END-CREATE CUSTREL TABLE
	
	--STEP-4-START-CREATE DORM_DET TABLE
		v_STAGE  := 401;
		v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_DORM_DET';
	
		
		SELECT COUNT(*) INTO v_ExistCount FROM user_tables
		WHERE TABLE_NAME = 'DORM_DET';
	
		IF (v_ExistCount = 1 ) THEN
			v_STAGE  := 402;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_DELETE_DORM_DET';
			EXECUTE IMMEDIATE 'DROP TABLE DORM_DET';
		END IF;
		
		--IF (v_ExistCount = 0 ) THEN
			v_STAGE  := 403;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_DORM_DET';
			
			EXECUTE immediate 
			'CREATE TABLE "DORM_DET"
			(
			 "POST_UR_ID" NUMBER(4, 0),
			 "POST_UR_TIME" NUMBER(4, 0),
			 "PASS_UR_ID" NUMBER(4, 0),
			 "PASS_UR_TIME" NUMBER(4, 0),
			 "BR_CODE" NUMBER(4, 0),
			 "ACTNO" VARCHAR2(13),
			 "STATUS" VARCHAR2(1),
			 "RSTATUS" VARCHAR2(1),
			 "IR_NO" NUMBER(6, 0),
			 "TRAN_DATE" DATE,
			 "LAST_TR_DATE" DATE,
			 "TRAN_NO" NUMBER(6, 0)
			)';
			   
		   --STEP-4.1-START-ALTER DESTINATION TABLE
				v_STAGE  := 404;
				v_STAGE_TITLE  := 'DESTINATION_TABLE_ALTER_DORM_DET';
				
				SELECT COUNT(*) INTO v_ExistCount FROM user_tab_columns
				WHERE TABLE_NAME = 'DORM_DET' AND COLUMN_NAME = 'REF_KEY1';
				
				IF (v_ExistCount = 0 ) THEN
					v_STAGE  := 405;
						EXECUTE IMMEDIATE 'ALTER TABLE DORM_DET ADD (REF_KEY1 NUMBER(7,0) NULL)';
					v_STAGE  := 406;
						EXECUTE IMMEDIATE 'CREATE INDEX "DORM_DET_REFKEY_BE_IDX1" ON  "DORM_DET" ("REF_KEY1")';						
					
				END IF;
			--STEP-4.1-END-ALTER DESTINATION TABLE
	  --END IF;
	--STEP-4-END-CREATE DORM_DET TABLE
	
	--STEP-5-START-CREATE SIGNAUTH TABLE
		v_STAGE  := 501;
		v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_SIGNAUTH';
	
		
		SELECT COUNT(*) INTO v_ExistCount FROM user_tables
		WHERE TABLE_NAME = 'SIGNAUTH';
	
		IF (v_ExistCount = 1 ) THEN
			v_STAGE  := 502;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_DELETE_SIGNAUTH';
			EXECUTE IMMEDIATE 'DROP TABLE SIGNAUTH';
		END IF;
		
		--IF (v_ExistCount = 0 ) THEN
			v_STAGE  := 503;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_SIGNAUTH';
			
			EXECUTE immediate 
			'CREATE TABLE "SIGNAUTH"
			(
			 "ACTNO" VARCHAR2(13),
			 "IR_NO" NUMBER(6, 0),
			 "SR_NO" NUMBER(2, 0),
			 "TRAN_DATE" DATE,
			 "CUST_ID" VARCHAR2(13),
			 "CAPACITY" VARCHAR2(1),
			 "VALDATE" DATE
			)';
			   
		   --STEP-5.1-START-ALTER DESTINATION TABLE
				v_STAGE  := 504;
				v_STAGE_TITLE  := 'DESTINATION_TABLE_ALTER_SIGNAUTH';
				
				SELECT COUNT(*) INTO v_ExistCount FROM user_tab_columns
				WHERE TABLE_NAME = 'SIGNAUTH' AND COLUMN_NAME = 'REF_KEY1';
				
				IF (v_ExistCount = 0 ) THEN
					v_STAGE  := 505;
						EXECUTE IMMEDIATE 'ALTER TABLE SIGNAUTH ADD (REF_KEY1 NUMBER(7,0) NULL)';
					v_STAGE  := 506;
						EXECUTE IMMEDIATE 'CREATE INDEX "SIGNAUTH_REFKEY_BE_IDX1" ON  "SIGNAUTH" ("REF_KEY1")';						
					
				END IF;
			--STEP-5.1-END-ALTER DESTINATION TABLE
	  --END IF;
	--STEP-5-END-CREATE SIGNAUTH TABLE
	
	--STEP-6-START-CREATE CLOSEDET TABLE
		v_STAGE  := 601;
		v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_CLOSEDET';
	
		
		SELECT COUNT(*) INTO v_ExistCount FROM user_tables
		WHERE TABLE_NAME = 'CLOSEDET';
	
		IF (v_ExistCount = 1 ) THEN
			v_STAGE  := 602;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_DELETE_CLOSEDET';
			EXECUTE IMMEDIATE 'DROP TABLE CLOSEDET';
		END IF;
		
		--IF (v_ExistCount = 0 ) THEN
			v_STAGE  := 603;
			v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_CLOSEDET';
			
			EXECUTE immediate 
			'CREATE TABLE "CLOSEDET"
			(
			 "POST_UR_ID" NUMBER(4, 0),
			 "POST_UR_TIME" NUMBER(4, 0),
			 "PASS_UR_ID" NUMBER(4, 0),
			 "PASS_UR_TIME" NUMBER(4, 0),
			 "BR_CODE" NUMBER(4, 0),
			 "ACTNO" NVARCHAR2(13),
			 "STATUS" NVARCHAR2(1),
			 "IR_NO" NUMBER(6, 0),
			 "TRAN_DATE" DATE,
			 "TRAN_CODE" NVARCHAR2(1),
			 "TRAN_NO" NUMBER(6, 0),
			 "BATCH_NO" NUMBER(6, 0),
			 "BLACTNO1" NVARCHAR2(13),
			 "BLACTNO2" NVARCHAR2(13),
			 "BLACTNO3" NVARCHAR2(13),
			 "BLACTNO4" NVARCHAR2(13),
			 "BLACTNO5" NVARCHAR2(13),
			 "TRAMT1" NUMBER(15, 2),
			 "TRAMT1_AMT_DC" NVARCHAR2(1),
			 "TRAMT2" NUMBER(15, 2),
			 "TRAMT2_AMT_DC" NVARCHAR2(1),
			 "TRAMT3" NUMBER(15, 2),
			 "TRAMT3_AMT_DC" NVARCHAR2(1),
			 "TRAMT4" NUMBER(15, 2),
			 "TRAMT4_AMT_DC" NVARCHAR2(1),
			 "TRAMT5" NUMBER(15, 2),
			 "TRAMT5_AMT_DC" NVARCHAR2(1),
			 "OLDINTRT" NUMBER(4, 2),
			 "PERIOD_DAYS" NUMBER(5, 0),
			 "PERIOD_MONTHS" NUMBER(5, 0),
			 "INT_RT" NUMBER(4, 2),
			 "PRIN_AMT" NUMBER(15, 2),
			 "PRIN_AMT_DC" NVARCHAR2(1),
			 "INT_AMT" NUMBER(15, 2),
			 "INT_AMT_DC" NVARCHAR2(1),
			 "INT_UPTO_DT" DATE,
			 "CHRG_AMT" NUMBER(15, 2),
			 "CHRG_AMT_DC" NVARCHAR2(1),
		     "CHRG_AMT1" NUMBER(15, 2),
			 "CHRG_AMT1_DC" NVARCHAR2(1),
			 "RDUE_AMT" NUMBER(15, 2),
			 "RDUE_AMT_DC" NVARCHAR2(1),
			 "AUTO_RENEW" NVARCHAR2(1),
			 "TDS_AMT" NUMBER(15, 2),
			 "TDS_AMT_DC" NVARCHAR2(1),
			 "SBRK_INT" NUMBER(15,2),
			 "BCINT_RT" NUMBER (4,2),
			 "LBRK_INT" NUMBER(15,2),
			 "TRAN_PART" VARCHAR2(30),
			 "TRAN_PART1" VARCHAR2(30)
			)';
			 			   
		   --STEP-6.1-START-ALTER DESTINATION TABLE
				v_STAGE  := 604;
				v_STAGE_TITLE  := 'DESTINATION_TABLE_ALTER_CLOSEDET';
				
				SELECT COUNT(*) INTO v_ExistCount FROM user_tab_columns
				WHERE TABLE_NAME = 'CLOSEDET' AND COLUMN_NAME = 'REF_KEY1';
				
				IF (v_ExistCount = 0 ) THEN
					v_STAGE  := 605;
						EXECUTE IMMEDIATE 'ALTER TABLE CLOSEDET ADD (REF_KEY1 NUMBER(7,0) NULL)';
					v_STAGE  := 606;
						EXECUTE IMMEDIATE 'CREATE INDEX "CLOSEDET_REFKEY_BE_IDX1" ON  "CLOSEDET" ("REF_KEY1")';						
					
				END IF;
			--STEP-6.1-END-ALTER DESTINATION TABLE
	  --END IF;
	--STEP-6-END-CREATE CLOSEDET TABLE
	
	COMMIT;
	UTL_FILE.PUTF(v_oFile,'-------MASTER CREATE : End Time %s-------%\n',TO_CHAR(SYSTIMESTAMP, 'HH12:MI:SS.FF4 AM'));
	UTL_FILE.FCLOSE(v_oFile);
EXCEPTION
	WHEN OTHERS THEN
		ROLLBACK;
		UPDATE CSV_CONFIG SET PROCESS_STATUS = 'N' WHERE STATUS='L';
		COMMIT;
		DBMS_OUTPUT.PUT_LINE('???????UNRECOVERABLE ERROR : STAGE#' || v_STAGE || '-Error- ' || SQLCODE || '-' || SQLERRM );
		UTL_FILE.PUTF(v_oFile,'\n???????UNRECOVERABLE ERROR : STAGE#%s-Error-%s-%s, End Time %s-------%\n',v_STAGE,SQLCODE,SQLERRM,TO_CHAR(SYSTIMESTAMP, 'HH12:MI:SS.FF4 AM'));
		UTL_FILE.FCLOSE(v_oFile);
END;
/
