create or replace 
FUNCTION FUN_GET_BE_OCCU_CODE
(
p_CL_OCCU_CODE VARCHAR2
)
RETURN VARCHAR2 IS
v_BE_OCCU_CODE VARCHAR2(1);
BEGIN

	v_BE_OCCU_CODE := '0';
	CASE p_CL_OCCU_CODE
		--SALARY
		WHEN '1' THEN v_BE_OCCU_CODE := '1';
		--AGRICULTURE.
		WHEN '2' THEN v_BE_OCCU_CODE := '5';
		--SELF / EMPLOYED.
		WHEN '3' THEN v_BE_OCCU_CODE := '2';
		--HOUSE HOLD
		WHEN '4' THEN v_BE_OCCU_CODE := '6';
		--SMALL BUSINESS
		WHEN '5' THEN v_BE_OCCU_CODE := '3';
		--BIG BUSINESS
		WHEN '6' THEN v_BE_OCCU_CODE := '3';
		--INDUSTRY
		WHEN '7' THEN v_BE_OCCU_CODE := 'I';
		ELSE v_BE_OCCU_CODE := '0'; 
	END CASE;

	RETURN v_BE_OCCU_CODE;
	
END FUN_GET_BE_OCCU_CODE;
/