create or replace 
FUNCTION FUN_GET_BE_ACTNO
(
	p_BRCODE NUMBER,
	p_GLCODE VARCHAR2,
	p_AGENTNO NUMBER,
	p_SLCODE NUMBER
	
)
RETURN VARCHAR2 IS
	v_BRANCH_ID NUMBER;
	v_BEACTNO VARCHAR2(13);
	v_CL_GLAC NUMBER(3);
	v_BE_GLAC NUMBER(3);
	v_BE_ACNO_PREFIX NUMBER;
	v_BE_ACNO NUMBER;
	v_BE_IAT VARCHAR2(4);
	v_ERROR BOOLEAN;
	v_temp_acno number;
	v_CONVERSION_NAME VARCHAR2(30);
		
BEGIN
  v_ERROR := FALSE;
  v_BRANCH_ID := p_BRCODE;
	--FETCH FROM 
	BEGIN
	IF(p_GLCODE IN(530001)) THEN
		IF(p_AGENTNO IS NULL)THEN
			SELECT BE_GLAC,BE_ACNO,BE_IAT INTO v_BE_GLAC,v_BE_ACNO,v_BE_IAT FROM GLMAP
			WHERE CL_GLAC=p_GLCODE AND BE_ACNO_PREFIX IS NULL; -- FOR AGENT NUMBER NULL PIGMY AGENT WISE ACCOUNT NUMBER.
		ELSE
			SELECT  BE_GLAC,BE_ACNO,BE_IAT INTO v_BE_GLAC,v_BE_ACNO,v_BE_IAT FROM GLMAP
			WHERE CL_GLAC = p_GLCODE AND p_AGENTNO=BE_ACNO_PREFIX; -- FOR AGENT NUMBER PRESENT ACCOUNT NUMBER WISE.
		END IF;
	ELSE
		SELECT  BE_GLAC,BE_ACNO,BE_IAT INTO v_BE_GLAC,v_BE_ACNO,v_BE_IAT FROM GLMAP
		WHERE CL_GLAC = p_GLCODE; -- FOR ACCOUNT NUMBER WISE.
	END IF;
		
	 EXCEPTION	  
		WHEN NO_DATA_FOUND THEN		
			BEGIN
				
		
				SELECT  BE_GLAC,BE_ACNO,BE_IAT INTO v_BE_GLAC,v_BE_ACNO,v_BE_IAT FROM GLMAP
				WHERE CL_GLAC = p_GLCODE;
				
			EXCEPTION
				WHEN NO_DATA_FOUND THEN
				v_ERROR := TRUE;           
				v_BEACTNO := NULL;         
			END ;			  
	END; 
	
	IF( NOT( v_ERROR ) ) THEN	
		/* IF(p_AC_TYPE IN(36,51)) THEN
			IF(LENGTH(p_AC_NO)=3)THEN
				v_BEACTNO := CONCAT(CONCAT(LPAD(v_BRANCH_ID,4,'0'),LPAD(v_BE_GLAC,3,'0')),  LPAD(SUBSTR(p_AC_NO,1,1),6,'0')) ;
			ELSIF(LENGTH(p_AC_NO)=4)THEN
				v_BEACTNO := CONCAT(CONCAT(LPAD(v_BRANCH_ID,4,'0'),LPAD(v_BE_GLAC,3,'0')),  LPAD(SUBSTR(p_AC_NO,1,2),6,'0')) ;
			ELSIF(LENGTH(p_AC_NO)=5)THEN
				v_BEACTNO := CONCAT(CONCAT(LPAD(v_BRANCH_ID,4,'0'),LPAD(v_BE_GLAC,3,'0')),  LPAD(SUBSTR(p_AC_NO,1,3),6,'0')) ;
			END IF;
		ELSE */
			v_BEACTNO := CONCAT(CONCAT(LPAD(v_BRANCH_ID,4,'0'),LPAD(v_BE_GLAC,3,'0')),  LPAD(NVL(v_BE_ACNO,p_SLCODE),6,'0')) ;
	--	END IF;
	END IF;
	
	RETURN v_BEACTNO;

END FUN_GET_BE_ACTNO;
/