
create or replace 
FUNCTION FUN_GET_EMI
(
	v_SANC_AMT NUMBER,
	v_INTERESTRATE NUMBER,
	v_PERIODVALUE NUMBER
)

RETURN VARCHAR2 IS
	v_ANNUAL_RATE number;
	v_POWER number;
	v_BASE number;
	v_EMI number;
	v_DENO number;
	
	
BEGIN
	--v_SANC_AMT :=NULL;
	v_ANNUAL_RATE:=NULL;
	--v_INTERESTRATE := NULL;
	v_POWER:= NULL;
	--v_PERIODVALUE := NULL;
	v_BASE:= NULL;
	v_EMI:=NULL;
	--FETCH FROM 
	
		v_ANNUAL_RATE:=v_INTERESTRATE/1200;
		v_POWER:=POWER((1+v_ANNUAL_RATE),v_PERIODVALUE);
		v_DENO:=v_POWER-1;
		v_BASE:=v_POWER/v_DENO;
		v_EMI:=v_SANC_AMT*v_ANNUAL_RATE*v_BASE;
		v_EMI := ROUND(v_EMI);
	RETURN v_EMI;
	
END FUN_GET_EMI;
/