create or replace 
FUNCTION FUN_GET_CL_AC_SUB
(
p_AC_TYPE NUMBER,
p_AC_NO NUMBER
)
RETURN NUMBER IS
v_AC_SUB NUMBER;

BEGIN

BEGIN
SELECT AC_SUB INTO v_AC_SUB FROM ALL_AC_MAS WHERE AC_TYPE = p_AC_TYPE AND AC_NO=p_AC_NO;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    v_AC_SUB := 0;
END;
RETURN v_AC_SUB;

END FUN_GET_CL_AC_SUB;
/