create or replace 
FUNCTION FUN_GET_BE_CODE
(
p_BE_GR_CODE VARCHAR2,
p_CL_PARENT_CODE VARCHAR2, 
p_CL_CODE VARCHAR2
)
RETURN VARCHAR2 IS
v_BE_CODE VARCHAR2(3);

BEGIN

	BEGIN
		SELECT BE_CODE INTO v_BE_CODE  FROM BE_CODES_MAP
		WHERE BE_GR_CODE = p_BE_GR_CODE AND CL_PARENT_CODE = p_CL_PARENT_CODE AND CL_CODE = p_CL_CODE ;
		
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
			v_BE_CODE := NULL;
	END;
  RETURN v_BE_CODE;

END FUN_GET_BE_CODE;
/