create or replace 
FUNCTION FUN_GET_CL_AC_CODE
(
p_AC_TYPE NUMBER
)
RETURN VARCHAR2 IS
v_CL_AC_CODE VARCHAR2(2);

BEGIN

BEGIN
SELECT CL_AC_CODE INTO v_CL_AC_CODE FROM GLMAP WHERE CL_AC_TYPE = p_AC_TYPE AND ROWNUM=1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    v_CL_AC_CODE := NULL;
END;
RETURN v_CL_AC_CODE;

END FUN_GET_CL_AC_CODE;
/