create or replace 
FUNCTION FUN_REPLACE_CHAR
(
p_STRING VARCHAR2
)
RETURN VARCHAR2 IS
v_STRING VARCHAR2;
BEGIN
	-- REPALCE 
	v_STRING := REPLACE(p_STRING, CHAR(10),'');
	-- REPLACE
	v_STRING := REPLACE(v_STRING, CHAR(13),'');	
	-- REPLACE '|' WITH SPACE' ' 
	v_STRING := REPLACE(v_STRING,'|',' ');	
	RETURN v_STRING;
END FUN_REPLACE_CHAR;
/