create or replace 
FUNCTION FUN_GET_ACTIVE_BRANCH_CODE
RETURN VARCHAR2 IS
v_BRCODE VARCHAR2(4);

BEGIN

SELECT BRCODE INTO v_BRCODE
FROM CSV_CONFIG
WHERE STATUS = 'L';

RETURN v_BRCODE;
END FUN_GET_ACTIVE_BRANCH_CODE ;
/