
create or replace 
FUNCTION FUN_GET_BE_ACTNO
(
	p_BRCODE NUMBER,  
	p_GLCODE VARCHAR2,
	p_SLCODE NUMBER
)
RETURN VARCHAR2 IS
	v_BRANCH_ID NUMBER;
	v_BEACTNO VARCHAR2(13);
	v_CL_GLAC NUMBER(3);
	v_BE_GLAC NUMBER(3);
	v_BE_ACNO NUMBER;
	v_BE_IAT VARCHAR2(4);
	v_ERROR BOOLEAN;
	v_temp_acno number;
	v_CONVERSION_NAME VARCHAR2(30);
	v_agent_id  NUMBER (6,0);
	v_SUB_ACCOUNT NUMBER(6,0);
	v_agentprefix NUMBER(2,0);
BEGIN
  v_ERROR := FALSE;
  v_BE_ACNO:= NULL;
  v_BRANCH_ID := p_BRCODE;
	--FETCH FROM 
	BEGIN
		
	-- v_BRCODE := FUN_GET_ACTIVE_BRANCH_CODE();
		SELECT  BE_GLAC, BE_ACNO, BE_IAT INTO v_BE_GLAC, v_BE_ACNO, v_BE_IAT FROM GLMAP
		WHERE CL_GLAC = p_GLCODE;
		
		
	EXCEPTION	  
		WHEN NO_DATA_FOUND THEN		
			BEGIN
				
		
				SELECT  BE_GLAC, BE_ACNO, BE_IAT INTO v_BE_GLAC, v_BE_ACNO, v_BE_IAT FROM GLMAP
				WHERE CL_GLAC = p_GLCODE;
				
			EXCEPTION
				WHEN NO_DATA_FOUND THEN
				v_ERROR := TRUE;           
				v_BEACTNO := NULL;         
			END ;			  
	END;
	
	IF( NOT( v_ERROR ) ) THEN	
		v_BEACTNO := CONCAT(CONCAT(LPAD(v_BRANCH_ID,4,'0'),LPAD(v_BE_GLAC,3,'0')),LPAD(NVL(v_BE_ACNO,p_ACNO),6,0)) ;	
	END IF;
	
	RETURN v_BEACTNO;

END FUN_GET_BE_ACTNO;
/