create or replace 
FUNCTION FUN_GET_CL_AC_TYPE
(
p_AC_CODE VARCHAR2
)
RETURN NUMBER IS
v_CL_AC_TYPE NUMBER;

BEGIN

BEGIN
SELECT CL_AC_TYPE INTO v_CL_AC_TYPE FROM GLMAP WHERE CL_AC_CODE = p_AC_CODE AND ROWNUM=1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    v_CL_AC_TYPE := 0;
END;
RETURN v_CL_AC_TYPE;

END FUN_GET_CL_AC_TYPE;
/