create or replace 
FUNCTION FUN_IS_CUST_NAME_VALID
(
p_CUST_NAME VARCHAR2
)
RETURN NUMBER IS
v_VALID NUMBER;

BEGIN

	v_VALID := 1;
	IF ( p_CUST_NAME = 'DIRECT DEPOSITS' ) THEN
		v_VALID := 0;
	ELSIF   ( p_CUST_NAME = 'OTHER ACCOUNTS' ) THEN
		v_VALID := 0;
	END IF;

RETURN v_VALID;

END FUN_IS_CUST_NAME_VALID;
/