DECLARE
v_ExistCount NUMBER := 0;
BEGIN


DBMS_OUTPUT.PUT_LINE ('....START...constructing BE-Constitution Codes.....');

--DELETE RECORDS IF EXIST

	SELECT COUNT(*) INTO v_ExistCount FROM user_tables
	WHERE TABLE_NAME = 'BE_CONST_CODE';
	
	IF (v_ExistCount = 1 ) THEN
		EXECUTE IMMEDIATE 'DELETE FROM BE_CONST_CODE';
	END IF;

--STEP-2--START-INSERT DATA TO BE_CONST_CODE
INSERT INTO BE_CONST_CODE ("CONST_CODE", "TITLE") VALUES ('1','Public Individual');
/*Modified by:
			AUTHOR:PRACHI BARGAJE
			DATE:14-03-2016
			DRESCRIPTION:HERE WE ARE REMOVING BANK AND WIDOW AS A CONST_CODE
		*/
--INSERT INTO BE_CONST_CODE ("CONST_CODE", "TITLE") VALUES ('B','Bank');
INSERT INTO BE_CONST_CODE ("CONST_CODE", "TITLE") VALUES ('C','Senior Citizen');
INSERT INTO BE_CONST_CODE ("CONST_CODE", "TITLE") VALUES ('E','Employee');
INSERT INTO BE_CONST_CODE ("CONST_CODE", "TITLE") VALUES ('F','Firm');
INSERT INTO BE_CONST_CODE ("CONST_CODE", "TITLE") VALUES ('S','Society');
INSERT INTO BE_CONST_CODE ("CONST_CODE", "TITLE") VALUES ('R','Credit Society');
INSERT INTO BE_CONST_CODE ("CONST_CODE", "TITLE") VALUES ('T','Trust');
INSERT INTO BE_CONST_CODE ("CONST_CODE", "TITLE") VALUES ('O','Other');
--STEP-2-END-INSERT DATA TO BE_CONST_CODE
DBMS_OUTPUT.PUT_LINE ('....built BE_CONST_CODE with default records.....');
DBMS_OUTPUT.PUT_LINE ('....NOTE - If required, you need to update constitution codes before calling the conversion process.....');
--STEP-2--END-INSERT DATA TO GLMAP
DBMS_OUTPUT.PUT_LINE ('....END...constructing BE-Constitution Codes.....');

END;
/