SET FLUSH ON;
SET SERVEROUTPUT ON;
DECLARE
	vTablecount NUMBER := 0;
	vIdexCount NUMBER := 0;
	v_STAGE NUMBER := 0;
	v_STAGE_TITLE VARCHAR2(50) := '';

BEGIN
	--STEP-1-START-CREATE STUDENTMASTER TABLE
	v_STAGE  := 101;
	v_STAGE_TITLE  := 'DESTINATION_TABLE_DELETE_STUDENTMASATER';
					DBMS_OUTPUT.PUT_LINE('***** START CREATE STUDENTMASTER *****');
					SELECT COUNT(*) INTO vTablecount FROM USER_TABLES
					WHERE TABLE_NAME = 'STUDENTMASTER';

					IF (vTablecount = 1) THEN 
					EXECUTE IMMEDIATE 'DROP TABLE STUDENTMASTER';
					END IF; 
		
	    v_STAGE  := 102;
		v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_STUDENTMASTER';
				EXECUTE IMMEDIATE
				'CREATE TABLE "STUDENTMASTER" 
					(
					"PRN" NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
					"LONG_NAME" VARCHAR2(45) NOT NULL,
					"F_NAME" VARCHAR2(15),
					"M_NAME" VARCHAR2(15),
					"L_NAME" VARCHAR2(15),
					"STATUS" VARCHAR2(1),
					"TRAN_DT" DATE NOT NULL,
					"DOB" DATE NOT NULL,	
					"BIRTH_PLACE" VARCHAR2(15),
					"EMAIL" VARCHAR2(20),
					"GENDER" VARCHAR2(10),
					"GRADE_LEVEL" VARCHAR2(2),
					"MOTHER_NAME" VARCHAR2(40),
					"FATHER_NAME" VARCHAR2(40),
					"FATHER_MOBILE" NUMBER(10),
					"MOTHER_MOBILE" NUMBER(10),
					"PANCARD" VARCHAR(10),
					"AADHAR" NUMBER(12),
					"ADDRESS" VARCHAR2(40) NOT NULL,
					"STATE" VARCHAR2(1),
					"DIST" VARCHAR2(1),
					"CITY" VARCHAR2(15),
					"PINCODE" NUMBER(6)
					)';
				DBMS_OUTPUT.PUT_LINE('***** STUDENTMASTER TABLE CREATED *****');
				
		--STEP-2-START-CREATE STUDENTMASTER INDEX 
		
		v_STAGE  := 103;
		v_STAGE_TITLE  := 'DESTINATION_TABLE_CREATE_INDEX';
				DBMS_OUTPUT.PUT_LINE('***** START-CREATE STUDENTMASTER INDEX *****');
				SELECT COUNT(*) INTO vIdexCount FROM USER_INDEXES WHERE INDEX_NAME='IDX_AADHAR_MOBILE';
				
				IF (vIdexCount = 0) THEN
					EXECUTE IMMEDIATE 'CREATE index IDX_AADHAR_MOBILE ON STUDENTMASTER (TRAN_DT,AADHAR)';
		DBMS_OUTPUT.PUT_LINE('***** STUDENTMASTER INDEX CREATED *****');
				END IF;
				
		--STEP-3-START-CREATE-  
				
				
				
				
	COMMIT;		
EXCEPTION
WHEN OTHERS THEN
		ROLLBACK;
		COMMIT;
		DBMS_OUTPUT.PUT_LINE('???????UNRECOVERABLE ERROR : STAGE#' || v_STAGE || '-Error- ' || SQLCODE || '-' || SQLERRM );
		--UTL_FILE.PUTF(v_oFile,'\n???????UNRECOVERABLE ERROR : STAGE#%s-Error-%s-%s, End Time %s-------%\n',v_STAGE,SQLCODE,SQLERRM,TO_CHAR(SYSTIMESTAMP, 'HH12:MI:SS.FF4 AM'));
		--UTL_FILE.FCLOSE(v_oFile);	
END;
/


