SET DEFINE ON
SET VERIFY OFF;
SET SERVEROUTPUT ON;
SET HEADING OFF;
SET FEEDBACK OFF;
SET ECHO OFF;

CLEAR SCREEN;
PROMPT;
PROMPT;
PROMPT;
PROMPT ******************BANK EXPERT CSV EXPORT TOOL INITIALIZATION********************
PROMPT;
PROMPT ....please wait for some time....
PROMPT;
PROMPT ....GLMAP
@@'&1.INIT\CREATE_GLMAP.sql';
PROMPT ....constructing GLMAP data....
--@@'&1.INIT\INSERT_GLMAP.sql';
/* 
@@'&1.INIT\CREATE_NEW_BEACNO.sql';
PROMPT ....CSV_CONFIGURATION
@@'&1.INIT\CREATE_CSV_CONFIG.sql';
@@'&1.INIT\INSERT_CSV_CONFIG.sql';
PROMPT;
PROMPT ....CSV_MASTER
@@'&1.INIT\CREATE_CSV_MASTER.sql';
@@'&1.INIT\INSERT_CSV_MASTER.sql';
PROMPT;

PROMPT ....BE_CODES
@@'&1.INIT\CREATE_BE_CODES.SQL';
@@'&1.INIT\INSERT_BE_CODES.SQL';

PROMPT ....BE_CODES_MAP
@@'&1.INIT\CREATE_BE_CODES_MAP.SQL';
@@'&1.INIT\INSERT_BE_CODES_MAP.SQL';
PROMPT ... BE_CONST_CODE
@@'&1.INIT\CREATE_BE_CONST_CODE.SQL';
@@'&1.INIT\INSERT_BE_CONST_CODE.sql';

PROMPT ....creating functions ....
--@@'&1.INIT\SET_MEMBER_ID TO SUB_ACCOUNT_NO.SQL';
@@'&1.INIT\FUN_GET_ACTIVE_BRANCH_CODE.sql';
@@'&1.INIT\FUN_GET_BE_ACTNO.sql';
@@'&1.INIT\FUN_GET_BE_CODE.sql';
@@'&1.INIT\FUN_GET_BE_CONST_CODE.sql';
@@'&1.INIT\FUN_GET_BE_OCCU_CODE.sql';
@@'&1.INIT\FUN_GET_BE_OPRN_MODE.sql';
@@'&1.INIT\FUN_GET_CL_AC_CAT.SQL';
--@@'&1.INIT\FUN_GET_CL_AC_CODE.sql';
--@@'&1.INIT\FUN_GET_CL_AC_SUB.sql';
--@@'&1.INIT\FUN_GET_CL_AC_TYPE.sql';
@@'&1.INIT\FUN_GET_VALID_LCK_NO.sql';
@@'&1.INIT\FUN_GET_VALID_LCK_NO.sql'
-- @@'&1.INIT\FUN_GET_ROWS.sql';
-- update some field in ajit_nagari 
--@@'&1.INIT\FUN_GET_CL_POST_UR_ID.sql';
--@@'&1.INIT\FUN_GET_BE_CUST_ID.sql';
--@@'&1.INIT\FUN_GET_UPDATE_SUB_ACCOUNTS_NO.sql';
@@'&1.INIT\FUN_GET_CL_MEMBERS_ID.sql';
@@'&1.INIT\FUN_REPLACE_CHAR.sql';
@@'&1.INIT\FUN_GET_EMI.sql';
@@'&1.INIT\CREATE_CSV_OUTPUT_DIR.SQL';
 */

PROMPT .... initialization done successfully ....
PROMPT;
PROMPT ----------THANK YOU-------------;
