PROMPT ----------MENU-------------;
SELECT CHR(9) || '(' || CAST(OBJECTID AS VARCHAR2(2)) || ')' || TITLE FROM CSV_MASTER
ORDER BY OBJECTID;
PROMPT;
ACCEPT CHOICE NUMBER FORMAT '99' PROMPT 'PUT YOUR CHOICE (0 to exit)='
PROMPT;
COLUMN SELECTED new_value SELECTION;
SET TERM off
SELECT
   CASE &CHOICE
        WHEN 0 THEN 'EXIT'
		WHEN 1 THEN 'PL_SQL_TEST_PROGRAM\test_prog_Sum'
		WHEN 2 THEN 'AGENT\AGENTMST_MAIN'
		WHEN 3 THEN 'CUSTOMER\CUSTOMER_MAIN'
		WHEN 4 THEN 'KYCMAST\KYCMAST_MAIN'
		WHEN 5 THEN 'ACCOUNT\ACCOUNT_MAIN'
		WHEN 6 THEN 'SIGN\SIGN_MAIN'
		WHEN 7 THEN 'PHOTO\PHOTO_MAIN'	
		WHEN 8 THEN 'CASH_SCR\CASH_SCR_MAIN'
		WHEN 9 THEN 'TRNF_SCR\TRNF_SCR_MAIN'
		WHEN 10 THEN 'TRAN\TRAN_MAIN'
		
		ELSE 'Exit'
  END SELECTED 
FROM DUAL;
SET TERM ON
-- execute the selected script
PROMPT ...calling the script : '&1.&SELECTION'
PAUSE 'press any key to continue';
CLEAR BUFFER;
@@'&1&SELECTION' '&1';
@@Menu.sql;
