PROMPT ----------MENU-------------;
SELECT CHR(9) || '(' || CAST(OBJECTID AS VARCHAR2(2)) || ')' || TITLE FROM CSV_MASTER
ORDER BY OBJECTID;
--PROMPT PUT YOUR CHOICE (0 to exit );
--ACCEPT CHOICE
PROMPT;
ACCEPT CHOICE NUMBER FORMAT '99' PROMPT 'PUT YOUR CHOICE (0 to exit)='
PROMPT;
--ACCEPT v_Choice NUMBER format '0' PROMPT 'PUT YOUR CONVERSION CHOICE:'
--PROMPT;
-- bind a substitution variable SELECTION to a SQL column
COLUMN SELECTED new_value SELECTION;
-- do if then else with SQL
-- the selected value is the name of the script to be executed
SET TERM off
SELECT
   CASE &CHOICE
        WHEN 0 THEN 'EXIT'
		WHEN 1 THEN 'NPA\NPA_MAIN'
		WHEN 2 THEN 'AGENT\AGENTMST_MAIN'
		WHEN 3 THEN 'CUSTOMER\CUSTOMER_MAIN'
		WHEN 4 THEN 'KYCMAST\KYCMAST_MAIN'
		WHEN 5 THEN 'ACCOUNT\ACCOUNT_MAIN'
		WHEN 6 THEN 'SIGN\SIGN_MAIN'
		WHEN 7 THEN 'PHOTO\PHOTO_MAIN'	
		WHEN 8 THEN 'CASH_SCR\CASH_SCR_MAIN'
		WHEN 9 THEN 'TRNF_SCR\TRNF_SCR_MAIN'
		WHEN 10 THEN 'TRAN\TRAN_MAIN'
		WHEN 11 THEN 'CHEQUE\CHEQUE_MAIN'
		WHEN 12 THEN 'DEPOSIT\DEPOSIT_MAIN'
		WHEN 13 THEN 'LOAN\LOAN_MAIN'
		WHEN 14 THEN 'SECURITY\SECURITY_MAIN'
		WHEN 15 THEN 'PASSBOOK\PASSBOOK_MAIN'
		WHEN 16 THEN 'DPINTTBL\DPINTTBL_MAIN'
		WHEN 17 THEN 'LNINTTBL\LNINTTBL_MAIN'
		WHEN 18 THEN 'DD\DD_MAIN'
		WHEN 19 THEN 'OCC\OCC_MAIN'
		WHEN 20 THEN 'ICC\ICC_MAIN'
		WHEN 21 THEN 'AREA\AREA_MAIN'
		WHEN 22 THEN 'SHARES\SHARES_MAIN'
		WHEN 23 THEN 'LNGUAR\LNGUAR_MAIN'
		WHEN 24 THEN 'BANKMAST\BANKMAST_MAIN'
		WHEN 25 THEN 'LOCKER\LOCKER_MAIN'
		WHEN 26 THEN 'SMSMAST\SMSMAST_MAIN'
		WHEN 27 THEN 'EMPLOYEE\EMPLOYEE_MAIN'
		WHEN 28 THEN 'VALUER\VALUER_MAIN'
		WHEN 29 THEN 'COMMODITY\COMMODITY_MAIN'	
		WHEN 30 THEN 'USERS\USERMST_MAIN'
		WHEN 31 THEN 'ADDRESS_PROOF\ADDRESS_MAIN'
		WHEN 32 THEN 'ID_PROOF\ID_MAIN'
		WHEN 33 THEN 'INTHIST\INTHIST_MAIN'
		WHEN 34 THEN 'SI\SI_MAIN'
		WHEN 35 THEN 'IVST_DET\IVST_DET_MAIN'
		WHEN 36 THEN 'INSU_DET\INSU_MAIN'
		WHEN 37 THEN 'DEAFFUND\DEAFFUND_MAIN'
		WHEN 38 THEN 'IW_NTRT\IW_NTRT_MAIN'
		WHEN 39 THEN 'OW_NTRT\OW_NTRT_MAIN'
		WHEN 40 THEN 'STCKSTMT\STCKSTMT_MAIN'
		WHEN 41 THEN 'BILLTRAN\BILLTRAN_MAIN'
		WHEN 42 THEN 'ATTACH\ATTACH_MAIN'
		WHEN 43 THEN 'OTWD_SCR\OTWD_SCR_MAIN'
		WHEN 44 THEN 'INWD_SCR\INWD_SCR_MAIN'
		WHEN 45 THEN 'TDSRECOV\TDSRECOV_MAIN'
		WHEN 46 THEN 'TDSMAST\TDSMAST_MAIN'
		WHEN 47 THEN 'LRECEIPT\LRECEIPT_MAIN'
		WHEN 99 THEN 'UPDATES\UPDATES_MAIN'
		ELSE 'Exit'
  END SELECTED 
FROM DUAL;
SET TERM ON
-- execute the selected script
PROMPT ...calling the script : '&1.&SELECTION'
PAUSE 'press any key to continue';
CLEAR BUFFER;
@@'&1&SELECTION' '&1';
@@Menu.sql;
